### ISSUE TITLE
Nowe README.md

### ISSUE THREAD

**Issue by wbzyl** [pokonski/trekking#1]
Witam!

Prosiłbym abyś skasował Railsowe README. 

Zamiast README wstaw README.md i korzystając
z notacji Markdown krótko opisz funkcjonalność
aplikacji, dodaj linki do api z których korzystałeś
(z uwagą na co należy zwrócić uwagę, co należy
uważnie przeczytać…).

Napisz z jakich gemów korzystałeś.

Na laboratorium chciałbym abyś krótko opoiwedział
jak pisałeś aplikację. 

Ja na wykładzie w poniedziałek chciałbym ją pokazać.
Podeślij link na którym będzie wtedy działać.

*_Koniecznie uruchom aplikacje w trybie produkcyjnym. *_

Z pozdrowieniami

--W. Bzyl

**Comment by pokonski** [comment]
Witam

Dobrze, wszystko poustawiam tak jak należy, opiszę i do niedzieli wyślę 
Panu ostateczny link z aplikacją.

pozdrawiam
Piotr Okoński

**Comment by wbzyl** [comment]
Dziękuję.

**Comment by pokonski** [comment]
Dodałem README.

**Comment by pokonski** [comment]
Czy ostatecznie udało się Panu tworzyć ścieżki? Bo widziałem kilka 
pustych utworzonych przez Pana. Testowałem na wszystkich współczesnych 
przeglądarkach i u mnie nie było problemu ze stawianiem punktów na mapie.

Na czas wykładu serwer uruchomię pod adresem 
http://okonski.dyndns.org/trek tak jak poprzednim razem.

**Comment by wbzyl** [comment]
Tak. Trenowałem przed wykładem.

Przy okazji. Szablon aplikacji jest bardziej w HTML 4 niż w HTML 5 –
jest za dużo elementów div, a brakuje nav, articles itp.

Korzystałes z frameworka Bootstrap. Jak? Korzystałeś
z jakiegoś gemu, robiłeś poprawki ręcznie?
Opisz dokładniej Bootstrap w README.

Z pozdrowieniami

--W. Bzyl

**Comment by pokonski** [comment]
Dodałem nav i article. Wszystkich divów się nie pozbędę, bo większość jest używana do CSS grid i menu górnego, których strukturę wymusza Bootstrap.

**Comment by wbzyl** [comment]
Część div pozostanie. Powody są zwykle takie jak to opisałeś.
